name: workshop_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dotted_line: ^3.1.0
  flutter:
    sdk: flutter
  ds_podi:
    git:
      url: https://github.com/podiapp/ds_podi.git
      ref: main
  flutter_fortune_wheel:
    git:
      url: https://github.com/podiapp/flutter_fortune_wheel.git
      ref: main
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.0.6+1
  flutter_modular: ^5.0.3
  flutter_svg: ^1.1.0
  google_fonts: ^3.0.1
  intl: ^0.17.0
  logger: ^1.1.0
  mobx: 2.0.7+2
  qr_flutter: ^4.0.0
  uuid: ^3.0.6
  validators: ^3.0.0

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.7
  modular_test: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: PodiIcons
      fonts:
        - asset: assets/fonts/PodiIcons.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat/Montserrat-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat/Montserrat-BlackItalic.ttf
          style: italic
          weight: 900
